version: 1.2.2.{build}
branches:
  except:
  - roslyn
  - gh-pages
image: Visual Studio 2017
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_file_version: '{version}'
install:
- cmd: >-
    nuget restore src
build:
  project: msbuild.config
  verbosity: minimal
artifacts:
- path: build
- path: nuget
- path: nuget-beta